#!/usr/bin/env python

import sys
import json
import matplotlib.pyplot as plt

args = sys.argv
prog_name = args[0]
help_msg = """
usage: %s <spike_log>

Parse mig_mon spike log and generate graph.
""" % prog_name

def usage ():
    print help_msg
    sys.exit(1)

if len(args) != 2:
    usage()

spike_log = args[1]

data = []
spike_fd = open(spike_log)
while True:
    line = spike_fd.readline().strip()
    if not line:
        break
    data.append(line.split(","))

spike_fd.close()

start_ts = int(data[0][0])
results = map(lambda x: [int(x[0]) - start_ts, int(x[1])], data)
axis_x = [x[0] for x in results]
axis_y = [x[1] for x in results]
plt.plot(axis_x, axis_y, "b-", axis_x, axis_y, "ro")
plt.xlabel("Time (s)")
plt.ylabel("Downtime (ms)")
plt.title("200 Loops DPDK Live Migration Network Downtime")
plt.show()
